version: "3.0"

services:
    main:
        container_name: main
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5000:5000
            - 9229:9229
        command: npm run start:dev
        depends_on:
            - postgres-db
        restart: always

    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        env_file:
            - .env
        environment:
            - PG_DATA=/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: always
        volumes:
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data:
